[project]
site_name = "Zensical modals"
site_url = "https://apcamargo.github.io/zensical_modals"
repo_name = "apcamargo/zensical_modals"
nav = ["index.md"]
extra_css = ["stylesheets/extra.css"]
extra_javascript = [
  { path = "javascripts/modal.js", type = "module" },
]

[project.markdown_extensions]
attr_list = {}
md_in_html = {}
modal_block = {}
pymdownx.bracketspan = {}

[project.markdown_extensions."pymdownx.superfences"]

[project.theme]
language = "en"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "green"
accent = "green"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "black"
accent = "green"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"
